-- Disable rainbow delimiters initially. Can re-enable with keymap. Rationale is
--  - TreeSitter based syntax highlighting colors operator() and operator[]
--    calls which would not be noticeable when all braces are colored
--  - Often braces are simple enough that the coloring would be more distracting
--    than helpful.
-- The plugin has no way to specify disabled-by-default. Blacklisting or 'nil'
-- strategy would make it impossible to activate later.
--
-- Update: The operator highlighting currently has higher priority so everything
-- works out of the box. There is no longer a need to disable rainbow.

-- require('rainbow-delimiters').disable(0)
